### ISSUE TITLE
[2.2.0] craft variabele not available in extend template when plugin installed

### ISSUE THREAD

**Issue by jripmeester** [putyourlightson/craft-blitz-recommendations#17] opened 2024-03-12 11:31 UTC
Please provide a clear and concise description of what the bug is, including:
After we upgrade the plugin to 2.2.0 and craft to 4.8.1 we got an twig saying that the craft variable is no longer available. When we turn off the plugin it works as expected.

This is the stack trace:
Twig\Error\RuntimeError: Variable "craft" does not exist. in /var/www/html/templates/_boilerplate/_layouts/base-html-layout.twig:30
Stack trace:
#0 /var/www/html/storage/runtime/compiled_templates/c9/c9ae8a60deaab054677fa035ae436db8.php(44): __TwigTemplate_00e15e7a9355347d9d152f376923c231->{closure}()
#1 /var/www/html/vendor/twig/twig/src/Template.php(86): __TwigTemplate_00e15e7a9355347d9d152f376923c231->doGetParent(Array)
#2 /var/www/html/vendor/putyourlightson/craft-blitz-hints/src/services/HintsService.php(257): Twig\Template->getParent(Array)
#3 /var/www/html/vendor/putyourlightson/craft-blitz-hints/src/services/HintsService.php(208): putyourlightson\blitzhints\services\HintsService->createHintWithTemplateLine(Object(craft\fields\Assets))
#4 /var/www/html/vendor/putyourlightson/craft-blitz-hints/src/services/HintsService.php(177): putyourlightson\blitzhints\services\HintsService->_addFieldHint(194)
#5 /var/www/html/vendor/putyourlightson/craft-blitz-hints/src/services/HintsService.php(122): putyourlightson\blitzhints\services\HintsService->_checkBaseRelations(Object(craft\elements\db\AssetQuery))
#6 /var/www/html/vendor/putyourlightson/craft-blitz-hints/src/BlitzHints.php(96): putyourlightson\blitzhints\services\HintsService->checkElementQuery(Object(craft\elements\db\AssetQuery))
#7 [internal function]: putyourlightson\blitzhints\BlitzHints->putyourlightson\blitzhints\{closure}(Object(craft\events\CancelableEvent))
#8 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\CancelableEvent))
#9 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\elements\\...', 'beforePrepare', Object(craft\events\CancelableEvent))
#10 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2021): yii\base\Component->trigger('beforePrepare', Object(craft\events\CancelableEvent))
#11 /var/www/html/vendor/craftcms/cms/src/elements/db/AssetQuery.php(983): craft\elements\db\ElementQuery->beforePrepare()
#12 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1389): craft\elements\db\AssetQuery->beforePrepare()
#13 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#14 /var/www/html/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\AssetQuery))
#15 /var/www/html/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#16 /var/www/html/vendor/craftcms/cms/src/db/Query.php(275): yii\db\Query->one(NULL)
#17 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1613): craft\db\Query->one(NULL)
#18 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1635): craft\elements\db\ElementQuery->one()
#19 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\AssetQuery), 'one', Array, 'method', false, false)
#20 /var/www/html/storage/runtime/compiled_templates/4f/4f18057467ea857d683ef2a3ccdd6107.php(38): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\AssetQuery), 'one', Array, 'method')
#21 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_0fe16fd00a55799c4cc927c99c97ca5b->doDisplay(Array, Array)
#22 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /var/www/html/storage/runtime/compiled_templates/07/079e75720235abe19b66c9bfa45cc74a.php(90): Twig\Template->display(Array)
#24 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_9770e68485eadc28c743807a881df3de->block_content(Array, Array)
#25 /var/www/html/storage/runtime/compiled_templates/0a/0adf3c3b42c7589286a890b5f3fa07b8.php(115): Twig\Template->displayBlock('content', Array, Array)
#26 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_d3d9dd8b8b7a8720f139829283a3e9e3->block_bodyHtml(Array, Array)
#27 /var/www/html/storage/runtime/compiled_templates/c9/c9ae8a60deaab054677fa035ae436db8.php(204): Twig\Template->displayBlock('bodyHtml', Array, Array)
#28 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_00e15e7a9355347d9d152f376923c231->block_bodyContent(Array, Array)
#29 /var/www/html/storage/runtime/compiled_templates/a6/a6a52ae14503f64c8cb18f4fa41a6d19.php(91): Twig\Template->displayBlock('bodyContent', Array, Array)
#30 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_25098a5093ed7bf556faf5c6d1a9d008->block_htmlPage(Array, Array)
#31 /var/www/html/storage/runtime/compiled_templates/5e/5e006cff3c08a5480933fc964e4b8c57.php(98): Twig\Template->displayBlock('htmlPage', Array, Array)
#32 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_1b84846e7f7b66e80e885b106c46321c->doDisplay(Array, Array)
#33 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#34 /var/www/html/storage/runtime/compiled_templates/a6/a6a52ae14503f64c8cb18f4fa41a6d19.php(48): Twig\Template->display(Array, Array)
#35 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_25098a5093ed7bf556faf5c6d1a9d008->doDisplay(Array, Array)
#36 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#37 /var/www/html/storage/runtime/compiled_templates/c9/c9ae8a60deaab054677fa035ae436db8.php(52): Twig\Template->display(Array, Array)
#38 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_00e15e7a9355347d9d152f376923c231->doDisplay(Array, Array)
#39 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#40 /var/www/html/storage/runtime/compiled_templates/0a/0adf3c3b42c7589286a890b5f3fa07b8.php(48): Twig\Template->display(Array, Array)
#41 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d3d9dd8b8b7a8720f139829283a3e9e3->doDisplay(Array, Array)
#42 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#43 /var/www/html/storage/runtime/compiled_templates/07/079e75720235abe19b66c9bfa45cc74a.php(46): Twig\Template->display(Array, Array)
#44 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9770e68485eadc28c743807a881df3de->doDisplay(Array, Array)
#45 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#46 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#47 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#48 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#49 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('index', Array)
#50 /var/www/html/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate('index', Array)
#51 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('index', Array, 'site')
#52 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#53 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#54 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#55 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#56 /var/www/html/public_html/index.php(12): yii\base\Application->run()
#57 {main}

**Comment by bencroker** [comment] 2024-03-12 13:09
This appears to be a duplicate of https://github.com/putyourlightson/craft-blitz/issues/632, please follow along there.

**Closed as completed by bencroker** 2024-03-12 13:09 UTC
Labels: bug
